### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by NickHatBoecker** [veltman/clmystery#25]
Hey there,

just solved the game. Really nice idea!
I would love to translate it into German. Are you okay with this?

Best regards
Nick

**Comment by marcusmueller** [comment]
Hey @NickHatBoecker,

it is an excellent display of character ask whether the author is OK with that, and I think it's good you do – especially since the author might have technical input on how to do that.

Now, in light of everyday life being slightly complicated these days, and your issue having sat for 3 months:

Just go ahead. This project is licensed under the MIT license, which essentially means: you can do _whatever_ you want to do with the code, as long as you keep the LICENSE.md in there (don't translate that). 

When you've found a way to make the game work in *both* languages (i.e. without breaking the English version; however that might look in practice), I'd like to think you could make a _pull request_ to feed that back into this code repository. However, having done slight modifications that turned out to be complete overhauls, I'd recommend _not_ trying to start with maintaining compatibility here. Just fork this project, and get started.

**Comment by veltman** [comment]
@NickHatBoecker yes, you're welcome to translate it!
